param(
    [string]$Root = (Split-Path -Parent $PSScriptRoot)
)

$ErrorActionPreference = "Stop"
$repoRoot = (Resolve-Path $Root).Path
$hookDir = Join-Path $repoRoot ".git\hooks"
$hookPath = Join-Path $hookDir "post-commit"

if (-not (Test-Path (Join-Path $repoRoot ".git"))) {
    throw "No .git directory found at $repoRoot"
}

New-Item -ItemType Directory -Force -Path $hookDir | Out-Null

$hook = @'
#!/usr/bin/env sh
# NEXUS local post-commit runtime hygiene hook.
# Generated by scripts/install_nexus_git_hooks.ps1.
python -m nexus_gate.hygiene.runtime_churn --root . --apply --json > reports/nexus_runtime_hygiene_post_commit_latest.json 2>/dev/null || true
'@

$hook | Set-Content -Path $hookPath -Encoding ascii
Write-Host "[OK] Installed NEXUS post-commit runtime hygiene hook: $hookPath"
