#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
HOOK_DIR="${ROOT}/.git/hooks"
HOOK_PATH="${HOOK_DIR}/post-commit"

if [ ! -d "${ROOT}/.git" ]; then
  echo "No .git directory found at ${ROOT}" >&2
  exit 1
fi

mkdir -p "${HOOK_DIR}"
cat > "${HOOK_PATH}" <<'HOOK'
#!/usr/bin/env sh
# NEXUS local post-commit runtime hygiene hook.
# Generated by scripts/install_nexus_git_hooks.sh.
python -m nexus_gate.hygiene.runtime_churn --root . --apply --json > reports/nexus_runtime_hygiene_post_commit_latest.json 2>/dev/null || true
HOOK
chmod +x "${HOOK_PATH}"
echo "[OK] Installed NEXUS post-commit runtime hygiene hook: ${HOOK_PATH}"
